name: Nightly Generation

on:
  push:
    branches: [ nightly ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'jMonkeyEngine/sdk'
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: Grant execute permission for gradlew and others.
      run: chmod +x gradlew *.sh
      
    - name: Download the Engine
      run: ./build_engine.sh
      
    - name: Fix the Engine
      run: ./fix_engine.sh
      
    - name: Build the SDK
      run: ./gradlew buildSdk
      
    - name: Build Nightly NBMs
      env:
        NBM_SIGN_PASS: ${{ secrets.NBM_SIGN_PASS }}
      # For Stable, use set-spec-version
      run: ant -Dstorepass="$NBM_SIGN_PASS" -Dcatalog.base.url=https://github.com/jMonkeyEngine/sdk-update-center/releases/download/nightly_${{ github.run_id }} set-impl-version suite.nbms unset-impl-version
      
    - name: Upload nbms
      uses: softprops/action-gh-release@v1
      with:
        files: build/updates/*.nbm
        body: Nightlies built from Commit ${{ github.sha }}.
        tag_name: nightly_${{ github.run_id }}
        name: Master Nightlies ${{ github.run_id }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Checkout the XML Repository
      uses: actions/checkout@v2
      with:
        ref: nightly-xml
        path: xml
      
    - name: Setup Git for the commit
      run: git config user.email MeFisto94@users.noreply.github.com && git config user.name MeFisto94
      working-directory: xml
      
    - name: Overwrite the updates.xml
      # \cp to prevent an alias to cp -i (interactive)
      run: \cp -rf build/updates/updates.xml xml/updates.xml
      
    - name: Commit the updates.xml
      working-directory: ./xml
      run: git add updates.xml && git commit -m "Updating the nightlies to ${{ github.run_id}}" && git push
